skip_tags: true
version: 0.5.{build}
configuration: Release

# configure environment / install required software in build process
install:
  #- cinst nunit
  #- cinst 7zip.commandline
  #- cinst GitVersion.Portable
  #- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - ps: GitVersion /output buildserver /updateassemblyinfo true
  - ps: $env:GIT_PRE_RELEASE = !$env:GitVersion_BranchName.Equals("master")

nuget:
  account_feed: true
  project_feed: true

# restore nuget packages before build
before_build:
  - nuget restore .\HelperSharp.sln

# build configuration
build:
  project: .\HelperSharp.sln
  verbosity: minimal

# create nuget packages =]
after_build:
  - nuget pack .\HelperSharp\HelperSharp.csproj -OutputDirectory .\nuget
  - nuget pack .\HelperSharp.Mvc\HelperSharp.Mvc.csproj -OutputDirectory .\nuget
  - nuget pack .\HelperSharp.WebApi\HelperSharp.WebApi.csproj -OutputDirectory .\nuget

# push artifacts
artifacts:
  - path: .\src\nuget\*.nupkg

deploy:
  - provider: GitHub
    tag: v$(GitVersion_SemVer)
    release: v$(GitVersion_SemVer)
    auth_token:
      secure: N8V6KXkCcQFhvrfDUYgzK9WmFdT88Y6WlgSSo6MkGESrrto3feqZOGWvQ6BdWB9m
    draft: false
    prerelease: $(GIT_PRE_RELEASE)
    artifact: /.*\.nupkg/
